function fk_thigh_rot = autoFunc_fk_thigh_rot(in1,lc,in3)
%autoFunc_fk_thigh_rot
%    FK_THIGH_ROT = autoFunc_fk_thigh_rot(IN1,LC,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    24-Feb-2023 13:32:48

t1 = in1(1,:);
t2 = in1(2,:);
t4 = cos(t1);
t5 = cos(t2);
t6 = sin(t1);
t7 = sin(t2);
fk_thigh_rot = reshape([t5,t6.*t7,-t4.*t7,0.0,t4,t6,t7,-t5.*t6,t4.*t5],[3,3]);
