function d_fk_drho = autoFunc_d_fk_drho(in1,lc,in3)
%autoFunc_d_fk_drho
%    D_FK_DRHO = autoFunc_d_fk_drho(IN1,LC,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    24-Feb-2023 13:32:48

t1 = in1(1,:);
t2 = in1(2,:);
t3 = in1(3,:);
t5 = t2+t3;
t6 = cos(t5);
d_fk_drho = [-sin(t5);t6.*sin(t1);-t6.*cos(t1)];
